### ISSUE TITLE
Missing blank_penalty Configuration

### ISSUE THREAD

**Issue by parth-khiera** [k2-fsa/sherpa-onnx-go-linux#3]
I am in the process of shifting our infrastructure from Python to Go for better latency. However, I noticed that the blank_penalty configuration parameter, which is available in the Python API (see [online-decode-files.py#L239](https://github.com/k2-fsa/sherpa-onnx/blob/9ee2943ed45d9bb80bfd33f178aae7259d94188b/python-api-examples/online-decode-files.py#L239)), is missing in the Go package. This parameter is important for us.

Is there a way to configure blank_penalty in the Go package? I'm ready to contribute and make a PR if any package changes are needed to make it available.

Thank you!

**Comment by csukuangfj** [comment]
> I'm ready to contribute and make a PR if any package changes are needed to make it available.

Please follow how we add the following field
https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/csrc/offline-recognizer.h#L39

to add support for blank_penalty.
https://github.com/k2-fsa/sherpa-onnx/blob/9ee2943ed45d9bb80bfd33f178aae7259d94188b/sherpa-onnx/csrc/offline-recognizer.h#L41

----

You need to change the following files at the following places

1. https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/c-api/c-api.h#L429
2. https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/c-api/c-api.cc#L428
3. https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/go/sherpa_onnx.go#L423
4. https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/go/sherpa_onnx.go#L531
5. Done!

**Comment by parth-khiera** [comment]
Hey, 
Suggested changes worked, I am raising [this](https://github.com/k2-fsa/sherpa-onnx/pull/1232) PR for same. I was hoping it would be possible for you to release this before the end of the week as I have a deadline to release to my production infrastructure. Sorry for the urgency and understand if it is not possible but just wanted to keep you informed on my timeline. Let me know if I can help in anyway to achieve this. 
Thank you!

**Comment by csukuangfj** [comment]
>  I was hoping it would be possible for you to release this before the end of the week as I have a deadline to release to my production infrastructure. 

Just released a new version, v1.20.21

Please re-check.
@parth-khiera

**Comment by parth-khiera** [comment]
Thanks for the quick action! @csukuangfj 
Closing issue
